name: Release Train

on:
  workflow_dispatch:

jobs:
  call-release-train:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    uses: regatus/devops/.github/workflows/release-train.yml@main
    secrets: inherit